export enum actionTypes{
    GET_TODO_ITEMS_REQUEST,
    GET_TODO_ITEMS_DONE,
    POST_TODO_ITEM_REQUEST,
    POST_TODO_ITEM_DONE,
    DELETE_TODO_ITEM_REQUEST,
    DELETE_TODO_ITEM_DONE,
    MODIFY_TODO_ITEM_REQUEST,
    MODIFY_TODO_ITEM_DONE
}